### ISSUE TITLE
Green Divider | Home Page

### ISSUE THREAD

**Issue by kpatuto** [jmarchie/kp#10]
Exported svg file to the global assets folder

**Comment by jmarchie** [comment]
svg didn't scale well. created new one. 

<svg class="green-divider" width="100%">
            <rect height="100%" y="0" style="fill:#BBE8CA;" x="46%" width="8%"></rect>  
        </svg>

gave svg responsive height. 16px desktop, 10px tablet, and 6px on mobile. 
width will always be 8% of the viewport
