### ISSUE TITLE
Previous/Next Buttons | Tablet

### ISSUE THREAD

**Issue by kpatuto** [jmarchie/kp#15]
Scale the arrows 12% width

Add 12px padding between arrow and text

<img width="189" alt="screen shot 2018-10-13 at 6 21 00 pm" src="https://user-images.githubusercontent.com/44005305/46910576-f1edf700-cf14-11e8-8c23-595936d98ff0.png">

**Comment by jmarchie** [comment]
added padding and changed width to 22% for tablet

**Comment by kpatuto** [comment]
Width was 32%, Can you make it 20%

.project-arrows-right {
	**width: 20%;**
	padding-left: 12px;
}

<img width="196" alt="screen shot 2018-10-14 at 10 05 21 pm" src="https://user-images.githubusercontent.com/44005305/46926092-51273680-cffd-11e8-9b54-dbce3ec71750.png">

**Comment by jmarchie** [comment]
fixed
