### ISSUE TITLE
Project Info | Tablet

### ISSUE THREAD

**Issue by kpatuto** [jmarchie/kp#19]
Add padding between horizontal lines and text

.font-body {
	font-size: 12px;
	line-height: 18px;
	**padding-top: 18px;
	padding-bottom: 18px;
<img width="1982" alt="screen shot 2018-10-13 at 6 44 29 pm" src="https://user-images.githubusercontent.com/44005305/46910752-1f886f80-cf18-11e8-85e6-58260ba42c2e.png">
**
}

**Comment by jmarchie** [comment]
added padding to font-body

**Comment by kpatuto** [comment]
Can you make the padding bottom 18px;

.font-body {
	font-size: 12px;
	line-height: 18px;
	font-weight: 100;
	**padding-bottom: 18px;**
	padding-top: 12px;
}
