### ISSUE TITLE
Project Info Drop-Down | Mobile

### ISSUE THREAD

**Issue by kpatuto** [jmarchie/kp#20]
Add padding between lines and text

.font-body {
	font-size: 12px;
	line-height: 18px;
	color: #7c868e;
	font-family: museo-sans, sans-serif;
	font-weight: 100;
	**padding-top: 12px;
	padding-bottom: 12px;
<img width="1741" alt="screen shot 2018-10-13 at 6 55 46 pm" src="https://user-images.githubusercontent.com/44005305/46910837-9d00af80-cf19-11e8-83fd-0c73e33f48e1.png">
**
}
<img width="1741" alt="screen shot 2018-10-13 at 6 55 46 pm" src="https://user-images.githubusercontent.com/44005305/46910837-9d00af80-cf19-11e8-83fd-0c73e33f48e1.png">

**Comment by jmarchie** [comment]
added padding to mobile

**Comment by jmarchie** [comment]
fixed
