### ISSUE TITLE
Previous/Next Buttons | Mobile

### ISSUE THREAD

**Issue by kpatuto** [jmarchie/kp#21]
Make arrow width 10% and add 10px of padding

element {
	vertical-align: middle;
	**width: 10%;
	padding-right: 10px;
**
}
<img width="163" alt="screen shot 2018-10-14 at 12 58 55 pm" src="https://user-images.githubusercontent.com/44005305/46919707-113a6200-cfb1-11e8-8450-916fa3e6552e.png">

**Comment by jmarchie** [comment]
added padding and changed width to 16% for mobile

**Comment by jmarchie** [comment]
done
