### ISSUE TITLE
Footer | Mobile

### ISSUE THREAD

**Issue by kpatuto** [jmarchie/kp#22]
Remove line break from footer nav and copyright line

**Comment by jmarchie** [comment]
added class to disable break on mobile.

**Comment by kpatuto** [comment]
Can you make the footer links width 24%

.footer-links {
	**width: 26%;**
	margin-left: auto;
	margin-right: auto;
	padding-bottom: 7%;
}

<img width="374" alt="screen shot 2018-10-14 at 10 29 13 pm" src="https://user-images.githubusercontent.com/44005305/46926863-99942380-d000-11e8-9d11-ea94b6898d54.png">

**Comment by jmarchie** [comment]
fixed
