### ISSUE TITLE
Footer | Mobile

### ISSUE THREAD

**Issue by kpatuto** [jmarchie/kp#23]
Add 16px top and bottom padding to quotes

.quotes {
	fill: #bbe8ca;
	animation: color-me-in 10s linear infinite;
	float: none;
	width: 30%;
	margin-left: auto;
	margin-right: auto;
	**padding-top: 18px;
	padding-bottom: 18px;**
}

Change social links padding to 7%

.footer-links {
	width: 35%;
	margin-left: auto;
	margin-right: auto;
	**padding-bottom: 7%;**
}

<img width="416" alt="screen shot 2018-10-14 at 1 13 47 pm" src="https://user-images.githubusercontent.com/44005305/46919819-01238200-cfb3-11e8-984a-b8f6be12d8b2.png">

**Comment by jmarchie** [comment]
modified quotes and footer link padding
