### ISSUE TITLE
Project Info Button | Desktop

### ISSUE THREAD

**Issue by kpatuto** [jmarchie/kp#3]
Please change info button padding to 16px;

.info-btn {
    border: none;
    background: inherit;
    **padding-left: 16px;**
    color: #bbe8ca;

**Comment by kpatuto** [comment]
<img width="182" alt="screen shot 2018-10-13 at 4 41 13 pm" src="https://user-images.githubusercontent.com/44005305/46909921-9584da80-cf08-11e8-9ce6-0e6ba62d6346.png">

**Comment by jmarchie** [comment]
added padding
