### ISSUE TITLE
Project Info 

### ISSUE THREAD

**Issue by kpatuto** [jmarchie/kp#30]
Can you make the tablet padding 12px

.info-btn {
	border: 0;
	background: inherit;
	color: #bbe8ca;
	font-family: museo-sans,sans-serif !important;
	font-weight: 900 !important;
	**padding-left: 12px;**
}

<img width="379" alt="screen shot 2018-10-14 at 10 21 06 pm" src="https://user-images.githubusercontent.com/44005305/46926671-afedaf80-cfff-11e8-8267-e3af9f4969ad.png"

Can you make the mobile padding 8px

.info-btn {
	border: 0;
	background: inherit;
	color: #bbe8ca;
	font-family: museo-sans,sans-serif !important;
	font-weight: 900 !important;
	**padding-left: 8px;**
}

<img width="769" alt="screen shot 2018-10-14 at 10 22 11 pm" src="https://user-images.githubusercontent.com/44005305/46926686-c0058f00-cfff-11e8-941e-c9ff833615f5.png">

**Comment by jmarchie** [comment]
done
