### ISSUE TITLE
Project Info Drop-Down | Desktop

### ISSUE THREAD

**Issue by kpatuto** [jmarchie/kp#4]
Add 40px of top padding

.font-body {
	font-size: 12px;
	line-height: 18px;
	**padding-top: 40px;**

}

<img width="2161" alt="screen shot 2018-10-13 at 6 48 35 pm" src="https://user-images.githubusercontent.com/44005305/46910773-9f163e80-cf18-11e8-9de9-803433decad1.png">

**Comment by jmarchie** [comment]
added padding to desktop font-body
