### ISSUE TITLE
Previous/Next Buttons | Desktop

### ISSUE THREAD

**Issue by kpatuto** [jmarchie/kp#5]
Move arrow out of the span class

Add 16px padding between arrow and text
<img width="2253" alt="screen shot 2018-10-13 at 5 05 18 pm" src="https://user-images.githubusercontent.com/44005305/46909999-4b9cf400-cf0a-11e8-9dfa-7b5ea2c92b15.png">

**Comment by jmarchie** [comment]
moved arrow out of span and added padding
