### ISSUE TITLE
Nav Desktop

### ISSUE THREAD

**Issue by kpatuto** [jmarchie/kp#7]
Please make padding 48px;

.font-nav {
	font-size: 18px;
	color: #bbc7d7;
	text-decoration: none;
	**padding-left: 48px;**
	font-family: museo-sans-condensed, sans-serif;
	font-weight: 900;
	letter-spacing: 3px;
}

**Comment by kpatuto** [comment]
<img width="601" alt="screen shot 2018-10-13 at 5 14 17 pm" src="https://user-images.githubusercontent.com/44005305/46910052-6f146e80-cf0b-11e8-8e7a-6269d94469ae.png">

**Comment by jmarchie** [comment]
added padding for desktop and tablet
